server.port=8081
spring.application.name=drive_manager

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://cespinozamarinao_db_user:fUlMyuucWicJCirO@erascluster.thiwxyy.mongodb.net/eras_db?appName=erasCluster
spring.data.mongodb.auto-index-creation=true

# Google Drive Configuration
drive.service-account-credentials=classpath:drive-service-account.json
drive.base-folder-id=1EoH9pXpyt14TUt3te7-R9g2XGScFCFe_
# Public HTTPS URL Google will POST change notifications to.
# Leave empty for local dev. Set to your real URL (e.g. via Cloudflare Tunnel) when deploying.
drive.webhook-url=
ngrok.auth-token=2yccSlnPl36uWemOsMLZa3iraf7_5gBdhD15oSrWQ5w8x6Pvy
# Quartz Scheduler Configuration
spring.quartz.job-store-type=memory
spring.quartz.properties.org.quartz.scheduler.instanceName=quartzScheduler
spring.quartz.properties.org.quartz.threadPool.threadCount=10

# Cloudflare R2 Configuration
#
r2.account-id=dd965360a1e7c1efdfca8197d9c01c5e
r2.access-key-id=a7e72f30222456b764d2894c12eab562
r2.secret-access-key=5b4881643417234af254811c0ed355ce7d5f8eb9b41f034161517c9c280cdaaf
r2.bucket-name=drive-cards
r2.public-url=https://pub-dee88d2d50684500b02058de2df2b421.r2.dev

# Logging Configuration
logging.level.root=INFO
logging.level.com.drive.drive_manager=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
